In [1]:
import numpy as np


# fileId = open('mergeAttackFreeImperstion.txt', 'r')
# fileA = open('impersion_attack_label.txt','r')


fileId = open('mergeIdwithAttackFree.txt', 'r')
fileA = open('mergeAttackwithAttackFree.txt','r')

# fileId = open('IdDoswithAttackFree.txt', 'r')
# fileA = open('AttackDoswithAttackFree.txt','r')


# fileId = open('IdFuzzywithAttackFree.txt', 'r')
# fileA = open('AttackFuzzywithAttackFree.txt','r')


# fileId = open('IdSpoofwithAttackFree.txt', 'r')
# fileA = open('AttackSpoofwithAttackFree.txt','r')


filename = 'classifier_results_mixed_orginal.csv'


impersion_variable = False

detectList = []
counter = 1
graphList = []
ultimateGraphList = []
utlimateaDetectionList = []
graphCounter = 0
ll = []

messageSize = 200

for line in fileId:
  node = line.split()[0]




  graphList.append(node)


  if len(graphList) == messageSize:
    ultimateGraphList.append(graphList)






    graphList = []



ugl1 = ultimateGraphList

for line in fileA:
  attackChecking = line.split()[0]

  ll.append(attackChecking)




  detectList.append(attackChecking)




  if len(detectList) == messageSize:
    utlimateaDetectionList.append(detectList)


    detectList = []

udl1 = utlimateaDetectionList


print(len(ugl1))
print(len(udl1))

print(ugl1[0])
print(len(ugl1[0]))
print(len(udl1[0]))
print(udl1[0])
print(udl1[3])





82497
82497
['04b0', '05a0', '05a0', '02a0', '0260', '0080', '0081', '0165', '018f', '02b0', '0153', '0220', '0316', '0329', '0545', '043f', '0370', '0440', '0164', '04b1', '0316', '018f', '0260', '0080', '0081', '0165', '02a0', '02b0', '0329', '0153', '01f1', '0220', '0382', '0350', '04f2', '0545', '00a0', '00a1', '0370', '043f', '0440', '04f0', '05a2', '04f1', '05a2', '051a', '0690', '04b0', '0316', '018f', '0080', '0081', '0153', '0153', '0165', '0153', '0220', '0260', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0587', '05a0', '04b1', '0164', '0316', '0260', '02a0', '0080', '0081', '0164', '0165', '0153', '018f', '01f1', '0220', '02b0', '02c0', '0329', '0350', '0370', '0120', '0382', '0164', '043f', '0440', '04f2', '0517', '04f0', '0545', '05a2', '04b0', '0316', '0260', '018f', '0080', '0081', '0165', '0153', '01f1', '0220', '01f1', '02a0', '02b0', '0329', '0545', '043f', '0370', '0440', '0510', '04b1', '0164', '05e4', '0165', '02b0', '0080', '0081', '0153', '018f', '01

In [2]:
print(utlimateaDetectionList[80])

['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R']

In [3]:
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random
import torch
from scipy.sparse import csr_matrix
from torch_geometric.data import Data, DataLoader

def getPrClosBewtenIndegcenOutdegcen(uList,vList):

    G_for_new_added_features = nx.DiGraph()  # Create a directed graph

    edges = [(u, v) for u, v in zip(uList, vList)]

    G_for_new_added_features.add_edges_from(edges)

    pr = nx.pagerank(G_for_new_added_features, alpha = 0.8)
    closeness_centrality = nx.closeness_centrality(G_for_new_added_features)
    betweenness_centrality = nx.betweenness_centrality(G_for_new_added_features)
    in_deg_centrality = nx.in_degree_centrality(G_for_new_added_features) 
    out_deg_centrality = nx.out_degree_centrality(G_for_new_added_features) 
  
    pr = dict(sorted(pr.items(), reverse=False))
    closeness_centrality = dict(sorted(closeness_centrality.items(), reverse=False))
                                
    betweenness_centrality = dict(sorted(betweenness_centrality.items(), reverse=False))
    in_deg_centrality = dict(sorted(in_deg_centrality.items(), reverse=False))
    out_deg_centrality = dict(sorted(out_deg_centrality.items(), reverse=False))

    pr = np.mean(list(pr.values()))
    closeness_centrality = np.mean(list(closeness_centrality.values()))
    betweenness_centrality = np.mean(list(betweenness_centrality.values()))
    in_deg_centrality = np.mean(list(in_deg_centrality.values()))
    out_deg_centrality = np.mean(list(out_deg_centrality.values()))


    return pr, closeness_centrality, betweenness_centrality, in_deg_centrality, out_deg_centrality


    

/Users/maloyd1/miniforge3/lib/python3.10/site-packages/torch_geometric/typing.py:73: UserWarning: An issue occurred while importing 'torch-scatter'. Disabling its usage. Stacktrace: dlopen(/Users/maloyd1/miniforge3/lib/python3.10/site-packages/torch_scatter/_scatter_cpu.so, 0x0006): Symbol not found: __ZN5torch8autograd13_wrap_outputsERKNSt3__16vectorIN2at6TensorENS1_9allocatorIS4_EEEERKNS1_13unordered_setIPN3c1010TensorImplENS1_4hashISD_EENS1_8equal_toISD_EENS5_ISD_EEEESL_NSB_8ArrayRefINSB_8optionalIS4_EEEERKNS1_10shared_ptrINS0_4NodeEEENS1_8functionIFS7_S7_S7_EEE
  Referenced from: <42B69765-B776-38AC-B399-DC3BF2321957> /Users/maloyd1/miniforge3/lib/python3.10/site-packages/torch_scatter/_scatter_cpu.so
  Expected in:     <EEA9DBAE-D739-32BF-BF5C-B495A4B0502E> /Users/maloyd1/miniforge3/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib
  warnings.warn(f"An issue occurred while importing 'torch-scatter'. "
/Users/maloyd1/miniforge3/lib/python3.10/site-packages/torch_geometric/t

In [4]:
def filtering_List(list1,list2):
    
# Use list comprehensions to filter sublists based on 
    letter_to_remove = 'I'
    filtered_list1 = [sublist1 for sublist1, sublist2 in zip(list1, list2) if letter_to_remove not in sublist2]
    filtered_list2 = [sublist2 for sublist2 in list2 if letter_to_remove not in sublist2]

    # Print the filtered lists
    # print("Filtered List 1:", filtered_list1)
    # print("Filtered List 2:", filtered_list2)

    return filtered_list1,filtered_list2


#ugl,udl = filtering_List(ugl1,udl1)
ugl,udl = ugl1,udl1

In [5]:


print(set(np.array(udl).flatten()))

{'D', 'R', 'F', 'I', 'S'}


In [6]:
#Making graph from the 200 sequential of id and store them in a file as Graph adjacent list
from collections import defaultdict
import networkx as nx
import matplotlib.pyplot as plt
import random
import torch
from scipy.sparse import csr_matrix
from torch_geometric.data import Data, DataLoader
gAttackfree=nx.DiGraph()
gAttacked = nx.DiGraph()

lenugl = len(ugl)

counter = 0
gAttackfreeCounter = 0
gAttackedCounter = 0



allLabelList = []
graphFeatureList_5 = []
graphFeatureList_2 = []
uvList = []
DataList = []
for i in range(0,lenugl):
  uList = []
  vList = []
  attackFree = 1
  fList = []
  all_unique_nodes = list(set(ugl[i]))
  ln = len(all_unique_nodes)
  array = np.zeros((ln,ln))
  for j in range (0, len(ugl[i])-1):
     u = all_unique_nodes.index(ugl[i][j])
     v = all_unique_nodes.index(ugl[i][j+1])
     uList.append(u)
     vList.append(v)
   
  uvList.append([uList,vList])
  
  
  pr, closeness_centrality, betweenness_centrality, in_deg_centrality, out_deg_centrality = getPrClosBewtenIndegcenOutdegcen(uList,vList)

  # indeg, outdeg, pr, closeness_centrality, betweenness_centrality, in_deg_centrality, out_deg_centrality


  graphFeatureList_5.append([pr, closeness_centrality, betweenness_centrality, in_deg_centrality, out_deg_centrality])
  graphFeatureList_2.append([in_deg_centrality, out_deg_centrality])
  
  #'Flood', 'Fuz', 'R', 'Mal'

  for j in range (0,len(ugl[i])):
    if udl[i][j] == 'S' or udl[i][j] == 'I' or udl[i][j] == 'D' or udl[i][j] == 'F':
      attackFree = 0
      break

  y = attackFree
  allLabelList.append(attackFree)


  # if impersion_variable == True and y == 0:
  #   for m in range(30):
  #     graphFeatureList_5.append([pr, closeness_centrality, betweenness_centrality, in_deg_centrality, out_deg_centrality])
  #     graphFeatureList_2.append([in_deg_centrality, out_deg_centrality])
  #     allLabelList.append(attackFree)

 


  








print(len(graphFeatureList_5))
print(len(graphFeatureList_2))
print(len(allLabelList))
print(allLabelList.count(0))
print(allLabelList.count(1))








82497
82497
82497
23663
58834


In [7]:
print(graphFeatureList_5[0])

print(graphFeatureList_2[0])

[0.026315789473684206, 0.2842343971466184, 0.07280306622411885, 0.07539118065433854, 0.07539118065433854]
[0.07539118065433854, 0.07539118065433854]


In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB, MultinomialNB, ComplementNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
import time
import csv

# Load your dataset or create a sample dataset
# X, y = load_your_data()

# Assuming you have already loaded your data into graphFeatureList_5 and allLabelList
# graphFeatureList_5, allLabelList = load_your_data()

# Split the data into training and testing sets (70% training, 30% testing)
X_train, X_test, y_train, y_test = train_test_split(graphFeatureList_5, allLabelList, test_size=0.3, random_state=42)

classifiers = {
    'GaussianNB': GaussianNB(),
    'MultinomialNB': MultinomialNB(),
    'ComplementNB': ComplementNB(),
    'LDA': LinearDiscriminantAnalysis(),
    'DecisionTree': DecisionTreeClassifier(),
    'GradientBoosting': GradientBoostingClassifier(),
    'XGBoost': XGBClassifier(use_label_encoder=False, eval_metric='logloss')
}

# Open a file to write the results
with open(filename, 'w', newline='') as file:
    writer = csv.writer(file)
    # Write the header
    writer.writerow(['Percentage', 'Classifier', 'Accuracy', 'Precision', 'Recall', 'F1 Score', 'Training Time (s)', 'Testing Time (s)'])

    for test_size_values in np.arange(0.3, 1.1, 0.3):
        X_train_p, X_test_p, y_train_p, y_test_p = train_test_split(X_train, y_train, train_size=test_size_values, random_state=42)

        print('Percentages:', test_size_values * 100)
        print('Count of class 1 in y_test:', y_test.count(1))
        print('Count of class 0 in y_test:', y_test.count(0))
        print('Length of y_test:', len(y_test))

        for name, clf in classifiers.items():
            # Train and evaluate the classifier
            start_time = time.time()
            clf.fit(X_train_p, y_train_p)
            end_time = time.time()
            training_time = end_time - start_time

            start_time = time.time()
            predictions = clf.predict(X_test)
            end_time = time.time()
            testing_time = end_time - start_time

            accuracy = accuracy_score(y_test, predictions)
            confusion = confusion_matrix(y_test, predictions)
            confusion[0, 0], confusion[1, 1] = confusion[1, 1], confusion[0, 0]  # Swap TN and TP

            precision = precision_score(y_test, predictions)
            recall = recall_score(y_test, predictions)
            f1 = f1_score(y_test, predictions)

            print(f'\n{name} Results:')
            print(f"Accuracy: {accuracy}")
            print(f"Confusion Matrix:\n{confusion}")
            print(f"Precision: {precision}")
            print(f"Recall: {recall}")
            print(f"F1 Score: {f1}")
            print(f"Training Time: {training_time} seconds")
            print(f"Testing Time: {testing_time} seconds")

            # Write the results to the file
            writer.writerow([test_size_values * 100, name, accuracy, precision, recall, f1,training_time, testing_time])

    # Evaluate classifiers with the entire training set
    print('Percentages 100%')
    X_train_p, y_train_p = X_train, y_train

    print('Count of class 1 in y_test:', y_test.count(1))
    print('Count of class 0 in y_test:', y_test.count(0))
    print('Length of y_test:', len(y_test))

    for name, clf in classifiers.items():
        start_time = time.time()
        clf.fit(X_train_p, y_train_p)
        end_time = time.time()
        training_time = end_time - start_time

        start_time = time.time()
        predictions = clf.predict(X_test)
        end_time = time.time()
        testing_time = end_time - start_time

        accuracy = accuracy_score(y_test, predictions)
        confusion = confusion_matrix(y_test, predictions)
        #confusion[0, 0], confusion[1, 1] = confusion[1, 1], confusion[0, 0]  # Swap TN and TP

        precision = precision_score(y_test, predictions)
        recall = recall_score(y_test, predictions)
        f1 = f1_score(y_test, predictions)

        print(f'\n{name} Results:')
        print(f"Accuracy: {accuracy}")
        print(f"Confusion Matrix:\n{confusion}")
        print(f"Precision: {precision}")
        print(f"Recall: {recall}")
        print(f"F1 Score: {f1}")
        print(f"Training Time: {training_time} seconds")
        print(f"Testing Time: {testing_time} seconds")

        # Write the results to the file
        writer.writerow([100, name, accuracy, precision, recall, f1, training_time, testing_time])


Percentages: 30.0
Count of class 1 in y_test: 17710
Count of class 0 in y_test: 7040
Length of y_test: 24750

GaussianNB Results:
Accuracy: 0.9531313131313132
Confusion Matrix:
[[16621    71]
 [ 1089  6969]]
Precision: 0.9957464653726336
Recall: 0.9385093167701863
F1 Score: 0.9662810301726643
Training Time: 0.014630794525146484 seconds
Testing Time: 0.017055034637451172 seconds

MultinomialNB Results:
Accuracy: 0.7155555555555555
Confusion Matrix:
[[17710  7040]
 [    0     0]]
Precision: 0.7155555555555555
Recall: 1.0
F1 Score: 0.8341968911917098
Training Time: 0.014965057373046875 seconds
Testing Time: 0.01829671859741211 seconds

ComplementNB Results:
Accuracy: 0.9035959595959596
Confusion Matrix:
[[16099   775]
 [ 1611  6265]]
Precision: 0.9540713523764371
Recall: 0.9090344438170526
F1 Score: 0.9310085588711543
Training Time: 0.014598846435546875 seconds
Testing Time: 0.01725602149963379 seconds

LDA Results:
Accuracy: 0.9503838383838383
Confusion Matrix:
[[16922   440]
 [  788  66

/Users/maloyd1/miniforge3/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [21:05:39] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)



XGBoost Results:
Accuracy: 0.9842424242424243
Confusion Matrix:
[[17608   288]
 [  102  6752]]
Precision: 0.983907018328118
Recall: 0.994240542066629
F1 Score: 0.9890467898668764
Training Time: 0.1921091079711914 seconds
Testing Time: 0.031358957290649414 seconds
Percentages: 60.0
Count of class 1 in y_test: 17710
Count of class 0 in y_test: 7040
Length of y_test: 24750

GaussianNB Results:
Accuracy: 0.9525252525252526
Confusion Matrix:
[[16603    68]
 [ 1107  6972]]
Precision: 0.9959210605242637
Recall: 0.9374929418407679
F1 Score: 0.9658241470579679
Training Time: 0.029201984405517578 seconds
Testing Time: 0.020176172256469727 seconds

MultinomialNB Results:
Accuracy: 0.7155555555555555
Confusion Matrix:
[[17710  7040]
 [    0     0]]
Precision: 0.7155555555555555
Recall: 1.0
F1 Score: 0.8341968911917098
Training Time: 0.034934043884277344 seconds
Testing Time: 0.018449068069458008 seconds

ComplementNB Results:
Accuracy: 0.9033535353535354
Confusion Matrix:
[[16087   769]
 [ 1623  

/Users/maloyd1/miniforge3/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [21:05:43] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)



XGBoost Results:
Accuracy: 0.9860606060606061
Confusion Matrix:
[[17640   275]
 [   70  6765]]
Precision: 0.9846497348590566
Recall: 0.9960474308300395
F1 Score: 0.9903157894736841
Training Time: 0.24733304977416992 seconds
Testing Time: 0.02843785285949707 seconds
Percentages: 89.99999999999999
Count of class 1 in y_test: 17710
Count of class 0 in y_test: 7040
Length of y_test: 24750

GaussianNB Results:
Accuracy: 0.9522020202020202
Confusion Matrix:
[[16595    68]
 [ 1115  6972]]
Precision: 0.9959191022024846
Recall: 0.9370412196499153
F1 Score: 0.9655834521281238
Training Time: 0.046053171157836914 seconds
Testing Time: 0.01954364776611328 seconds

MultinomialNB Results:
Accuracy: 0.7155555555555555
Confusion Matrix:
[[17710  7040]
 [    0     0]]
Precision: 0.7155555555555555
Recall: 1.0
F1 Score: 0.8341968911917098
Training Time: 0.04335498809814453 seconds
Testing Time: 0.018518924713134766 seconds

ComplementNB Results:
Accuracy: 0.902989898989899
Confusion Matrix:
[[16074   76

/Users/maloyd1/miniforge3/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [21:05:49] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)



XGBoost Results:
Accuracy: 0.9855353535353535
Confusion Matrix:
[[17650   298]
 [   60  6742]]
Precision: 0.9833964787162915
Recall: 0.9966120835686053
F1 Score: 0.9899601772393293
Training Time: 0.33832693099975586 seconds
Testing Time: 0.028729915618896484 seconds
Percentages 100%
Count of class 1 in y_test: 17710
Count of class 0 in y_test: 7040
Length of y_test: 24750

GaussianNB Results:
Accuracy: 0.9522828282828283
Confusion Matrix:
[[ 6973    67]
 [ 1114 16596]]
Precision: 0.9959791154053892
Recall: 0.9370976849237719
F1 Score: 0.9656416373316267
Training Time: 0.05458879470825195 seconds
Testing Time: 0.021564960479736328 seconds

MultinomialNB Results:
Accuracy: 0.7155555555555555
Confusion Matrix:
[[    0  7040]
 [    0 17710]]
Precision: 0.7155555555555555
Recall: 1.0
F1 Score: 0.8341968911917098
Training Time: 0.051142215728759766 seconds
Testing Time: 0.018066883087158203 seconds

ComplementNB Results:
Accuracy: 0.9033131313131313
Confusion Matrix:
[[ 6274   766]
 [ 1627 

/Users/maloyd1/miniforge3/lib/python3.10/site-packages/xgboost/core.py:158: UserWarning: [21:05:56] WARNING: /Users/runner/work/xgboost/xgboost/src/learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)



XGBoost Results:
Accuracy: 0.9857777777777778
Confusion Matrix:
[[ 6748   292]
 [   60 17650]]
Precision: 0.9837253371976369
Recall: 0.9966120835686053
F1 Score: 0.9901267811062492
Training Time: 0.34503602981567383 seconds
Testing Time: 0.027878761291503906 seconds


In [9]:
print(y_test.count(1))
print(y_test.count(0))
print(len(y_test))

17710
7040
24750
